### ISSUE TITLE
clang++ 4.0.0 static exceptions: undefined reference

### ISSUE THREAD

**Issue by elieux** [msys2/msys2#27]
<smf-> on IRC reports:

> Hi, I got a problem building with clang since updating to 4.0.0 using pacman.

```
#include <exception>
int main(int argc, char *argv[]) {
        throw std::exception();
}
```

```
[C:\temp]clang++ -static c.cpp
C:\Users\Password\AppData\Local\Temp\c-78151f.o:(.text+0x2e): undefined reference to `__imp___cxa_allocate_exception'
C:\Users\Password\AppData\Local\Temp\c-78151f.o:(.text+0x5a): undefined reference to `__imp___cxa_throw'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
```

Cc @mati865

**Comment by mati865** [comment]
It's the same bug as in this mail http://lists.llvm.org/pipermail/cfe-dev/2017-April/053530.html
```
$ clang++ exceptions.cc -static -S -O1 -o - | grep cxa
        callq   *__imp___cxa_allocate_exception(%rip)
        callq   *__imp___cxa_throw(%rip)

mati865@DESKTOP-0J8VPHJ MINGW64 ~/tmp
$ g++ exceptions.cc -static -S -O1 -o - | grep cxa
        call    __cxa_allocate_exception
        call    __cxa_throw
        .def    __cxa_allocate_exception;       .scl    2;      .type   32;    .endef
        .def    __cxa_throw;    .scl    2;      .type   32;     .endef
```
Currently using Clang with static libstdc++ and targeting Windows is asking for troubles and unfortunately I'm unable to fix it.

[offtopic]
@martell we probably have to fix these issues before we are able to build libc++ and libc++abi with Clang https://reviews.llvm.org/P7983$704

**Comment by elieux** [comment]
Thanks for explaining, Mati.

**Comment by martell** [comment]
I only really will have time this Sunday to work on this regression,
I have a few things to deliver for work and I am under pressure ATM :)

@mati865 I am already on that problem but for lld and not ld.
I already got this working for a team relying on this so I am obligated to fix this regression asap.
I have to reproduce a test case for lld so that rui or peter can fix what was broken.
http://lists.llvm.org/pipermail/llvm-dev/2017-May/112937.html

I also found the commit that I think caused the `_imp__` issues above https://reviews.llvm.org/rL289776
I started playing around with `-flto-visibility-public-std` also but didn't get too far yet.
It might be a good idea to email compnerd and ask his thoughts on the problem.
I would like to do this in a way that doesn't break the lto support he added for imports optimisation which might require an update to libstdc++ and libcxx and not clang itself.

As for the `float128` issue we have I emailed reid about this awhile back and he CC'd some intel engineers asking the correct approach to add support for windows (MSVC as well as Mingw)
but they never replied to the thread so the work on that died there.
I will try to follow up with him in the coming weeks on that also.

**Comment by martell** [comment]
@elieux you can work around it by making a weak alias. Example: `__imp___cxa_allocate_exception` to `__cxa_allocate_exception` via genlib or the new dlltool in llvm. So that might be useful until we get something more meaningful in tree

**Comment by mati865** [comment]
@martell examples from the mail aren't perfect but they can help narrow the bug.
I've tried to fully enable float128 but got only segfaults, downside of my current patch are broken tests.

**Comment by martell** [comment]
@mati865 I pinged that thread earlier and good some feedback on the mangling for float128 for windows. Reid also landed this with some additions for GCC defines https://reviews.llvm.org/rL304012
